server:
  port: 8080

spring:
  application:
    name: scmp-job-cs

# 日志配置
logging:
  level:
    com.scmp: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"